# Hierarchical Model, Mixture Distribution（階層モデル、混合分布）

2026-4-22

## 復習{-}

- 条件付き確率（密度）関数、周辺確率（密度）関数
- Bayesian Rule, Bayes estimators

## 階層モデル（pp.163~、現代数理統計の基礎 pp.65）


- 例： Binomial-Poisson Hierarchy

  - 分布と期待値

### 定理１：Conditional expectation（証明）

## Mixture Distributionの定義

- 例： Normal scale mixture distribution (現 pp.65)

- 例： Binomial-Poisson Hierarchy

  - 分布と期待値

- 例： Poisson-Gamma distribution (課題 $\rightarrow$ 4.32)

- 例： Noncentral $\chi^2$ distribution

- 例： Beta-binomial Hierarchy

### 定理２：Conditional variance identity（証明）

- 例： Beta-binomial Hierarchy

### EM algorithm (pp.327、現代数理統計の基礎 pp.263)

- 例： Multiple Poisson rates
- 定理*
- EM vs MLE*
- Missing data issue*
  
- Kullback–Leibler (KL) divergence: $KL(Q||P)$ - a measure of how much an approximating probability distribution $Q$ is different from a true probability distribution $P$ (現代数理統計の基礎 pp.195)

- Newton-Raphson method (現代数理統計の基礎 pp.262)

## コメント{-}

- Posterior 分布の導出
- 不確実性を階層的にモデル化

## 応用{-}

- GLMM: generalized linear mixed effects model（一般化線形混合モデル）

  - その特例： GLM
  - その一般化： Bayesian hierarchical model、階層ベイズ
  - Meta-analysis　データの統合
  
- Bayes analysis (pp.371)

  - Empirical Bayes analysis
  - Hierarchical Bayes analysis 
  - Gibbs sampling

- EM 
  
  - 混合分布の推定　(現代数理統計の基礎 pp.264 例11.4)
  - 分類モデル