# Order Statistics（順序統計量）

2026-4-28

## 復習{-}

- 統計量
- 中央値、分位数
- Rank
  - Nonparametric 検定 (based on rank)
    - Sign test/Wilcoxon Signed-rank test
    - Wilcoxon rank-sum test/U test

## 順序統計量（pp.226~；現代数理統計の基礎 pp.101）

- 定義、表記

  - Sample range, sample median
  - lower/upper quartile, interquartile range
  - Quantile function  分位関数*
  
## 定理1：順序統計量のPMF（導出）

## 定理2：順序統計量のCDF, PDF（導出）

- 例： Uniform distribution
- 最小統計量、最大統計量のPDF（現代数理統計の基礎 pp.104）*

## 定理3：順序統計量のJoint CDF, PDF*

- 例： Midrange, range

## コメント

- Empirical distribution function 経験分布関数（竹村：現代数理統計 pp.84）vs Distribution function 
  - $F_n(t)=\dfrac{1}{n}\sum_{i=1}^nI\{X_i\le t\} \xrightarrow{AS} F(t), \quad \forall t$
  - $\sqrt{n}(F_n(t)-F(t)) \xrightarrow{D} N(0, F(t)(1-F(t)))$
    - $P(\{X_i\le t\})=F(t)$
  - [Empirical process, semiparametric inference](https://people.eecs.berkeley.edu/~jordan/sail/readings/kosorok.pdf)

## 応用{-}

- Sign test
- Kolmogorov–Smirnov 検定 
  - https://ryonakagami.github.io/2023/07/02/Kolmogorov-Smirnov-test/
  - 2つの標本についてそれぞれの母集団の確率分布が一致しているかどうか
    - Goodness-of-Fit Tests: $\chi^2$ test