# Sufficient Statistics（十分統計量）

## 復習{-}

- 統計量
- Exponential family
- Likelihood
- Estimator, point estimation, unbiasedness
- Best unbiased estimator (UMVUE, uniform minimum variance unbiased estimator)
- Cramer-Rao inequality



## Three Principles of data reduction{-}
- Sufficiency principle
- Likelihood principle
- Equivariance principle
  - Formal sufficiency principle
  - Conditional principle
  - Formal likelihood principle
    - Formal likelihood principle corollary

## Sufficiency Principle (pp.272~)

- Principle

### Sufficient statistics 十分統計量
- 定義

#### Sufficient Statisticsに関する定理
- 例：Binomial, Normal, Order statistics   
  
#### Factorization Theorem 分解定理
- 例：Normal, Uniform, Normal considering 2 parameters

#### Exponential family に関する定理
  
### Minimal sufficient statistics 最小十分統計量

- 定義
- 例：Normal

#### Minimal Sufficient Statisticsに関する定理
  - 例：Normal, Uniform
  

### Ancillary Statistics 補助統計量
- 定義
- 例：Uniform, Location family, Scale family

### Complete Statistics 完全統計量

- Sufficient, Ancillary, Complete の定義
- Complete Statistics定義
- 例：Binomial, Uniform

#### Basu's Theorem (Ancillary Statistics $\bot$ Complete and minimal sufficient Statistics)

#### 定理（Exponential family）
  - 例：$E(g(\bf X))$, $\bar X\bot S^2$

#### 定理（Complete Statistics $\rightarrow$ Minimal sufficient statistics）

## Likelihood Principle

### Likelihood function

- 定義
- 例：Negative Binomial

#### Likelihood Principle 尤度原理
- 例：Normal fiducial dist.

#### Evidence function*

- Formal sufficiency principle
- Conditional principle
  - Binomial, negative binomial
  
- Formal likelihood principle
- Likelihood principle corollary
- Birnbaum' theorem
  - 例
  
## Equivariance Principle 同変原則*

- Equivarianceの定義
  - Measurement equivariance 測定同変性, formal invariance 形式的不変性

- Equivariance Principle
  - Binomial
  
### A group of transformation*
- 例

### Invariant under the group*

- Normal location invariant
- 例：binomial Bayes estimator(pp.332)


## 応用

- MLE, Bayesian Inference: remove  as much data as possible from the likelihood
- Find UMVUE (uniformly minimum variance unbiased estimator)
  - Unbiased + Sufficient $\Rightarrow$ Uniformly better unbiased estimator (Rao-Blackwell Theorem, pp. 342)
  - Unbiased + Sufficient + Complete $\Rightarrow$ Uniformly best unbiased estimator (Lehmann-Scheffé theorem ,pp.369)
- Likelihood ratio test
- Location-Scale family

## 参考資料

- [現代数理統計学の基礎-十分統計量](4/現代数理統計学の基礎-十分統計量.pdf)
- [現代数理統計学-十分統計量](4/現代数理統計学-十分統計量.pdf)