--- 
title: "Seminar Notes 2026"
author: "Yi Zhou"
date: "`r Sys.Date()`"
output:
  html_document:
    df_print: paged
documentclass: book
bibliography:
- book.bib
- packages.bib
link-citations: true
github-repo: "rstudio/bookdown-demo"
site: bookdown::bookdown_site
---

# 資料{-}

## スケジュール{-}

[Click here to download XLSX](Schedule2026.xlsx) 

## ゼミの資料（毎週更新）{-}

  - PDF [Click here to open folder](pdf/.)
  - Notes [Click here to open folder](notes/.)

## 参考資料{-}

  - Statistical Inference [Click here to open PDF](Textbook/Casella_Berger_Statistical_Inference.pdf)
    - 現代数理統計学 [Link to Kobe Univ. Lib](https://elib.maruzen.co.jp/elib/html/BookDetail/Id/3000105174;jsessionid=77611339D268556CDFB560D03E30F354?0)
    - 現代数理統計学の基礎 [Link to Kobe Univ. Lib](https://elib.maruzen.co.jp/elib/html/BookDetail/Id/3000050917?2)
    - 一般化線形モデル [Link to Kobe Univ. Lib](https://elib.maruzen.co.jp/elib/html/BookDetail/Id/3000031957?19)
    - ベイズ計算統計学 [Link to Kobe Univ. Lib](https://elib.maruzen.co.jp/elib/html/BookDetail/Id/3000027079?21)

  - Fundamentals of Biostatistics [Click here to open PDF](Textbook/Fundamentals of Biostatistics (8th Edition).pdf)
    - 医学統計学ハンドブック [Link to Kobe Univ. Lib](https://elib.maruzen.co.jp/elib/html/BookDetail/Id/3000068387?3)
    - 生存時間解析 [Link to Kobe Univ. Lib](https://elib.maruzen.co.jp/elib/html/BookDetail/Id/3000117213?16)
    - 実験計画法と分散分析 [Link to Kobe Univ. Lib](https://elib.maruzen.co.jp/elib/html/BookDetail/Id/3000027080?23)
    
  - An introduction to statistical learning 
    - with application in Python [Click here to open PDF](Textbook/ISLP_pyhton.pdf)
    - with application in R [Click here to open PDF](Textbook/ISLR_R.pdf)
    
  - 統計的因果推論 [Link to Kobe Univ. Lib](https://elib.maruzen.co.jp/elib/html/BookDetail/Id/3000034381?17)
    - 欠測データの統計解析 [Link to Kobe Univ. Lib](https://elib.maruzen.co.jp/elib/html/BookDetail/Id/3000031956?18)
    
  - Others [Click here to open folder](Textbook/.)
  
  
## 数理科学入門（統計学）の資料{-}

  - Slides [Click here to open PDF](Stats-slides/allslides.pdf)
  - Notes [Click here to open PDF](Stats-slides/allnotes.pdf)
  - 毎回の資料 [Click here to open folder](Stats-slides/slides-split/.)

## R{-}

  - R and RStudio installation: [https://posit.co/download/rstudio-desktop/](https://posit.co/download/rstudio-desktop/)
  - 授業の資料：[https://lec25.github.io/2026-1H609/](https://lec25.github.io/2026-1H609/)
  - etc.

## Python{-}

  - [https://yongks.github.io/python_bookdown/](https://yongks.github.io/python_bookdown/)
  - etc.
  
## Journals{-}

- Biostatistics

  - [Biometrics](https://academic.oup.com/biometrics)
  - [Statistics in Medicine](https://onlinelibrary.wiley.com/journal/10970258)
  - [Biostatistics](https://academic.oup.com/biostatistics)
  - [Statistical Methods in Medical Research (SMMR)](https://journals.sagepub.com/home/SMM)
  - [Journal of the American Statistical Association (JASA)](https://www.tandfonline.com/journals/uasa20)
  - [Biometrika](https://academic.oup.com/biomet)
  - [Journal of the Royal Statistical Society, Series B (Statistical Methodology) (JRSS B)](https://academic.oup.com/jrsssb?login=true)
  - [計量生物学](https://www.jstage.jst.go.jp/browse/jjb/-char/ja)
  - [統計数理](https://www.ism.ac.jp/editsec/toukei/index.html)
  
- Epidemiology
  
  - [American Journal of Epidemiology](https://academic.oup.com/aje)
  
- Bioinformatics

  - [Briefings in Bioinformatics](https://academic.oup.com/bib)
  - [Bioinformatics](https://academic.oup.com/bioinformatics)